apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: sample-spring-boot
spec:
  params:
  - name: github-repo-url
    value: $(body.repository.url)
  - name: APP_NAME
    value: $(body.repository.name)
  - name: github-repo-revision
    value: $(body.head_commit.id)
