apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: sample-boot
spec:
  params:
  - name: git-url
    description: The git repository url
    default: https://github.com/sachinayyar/tekton-spring-boot.git
  - name: git-revision
    description: The git revision
    default: master

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: tekton-argo-pipeline-$(uid)
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: tekton-argo-pipeline
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: IMAGE
        value: quay.io/sachinayyar/tekton-argocd:1
      workspaces:
      - name: source
      - name: maven-settings
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
