apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-trigger-template
spec:
  params:
  - name: git-repo
    description: The Git repository URL
    default: https://github.com/sachinayyar/tekton-spring-boot.git
  - name: git-commit
    description: The Git commit SHA
    default: abc123
  - name: git-branch
    description: The Git branch name
    default: master
  resourcetemplates:
  - name: source-repo
    resource:
      type: git
      params:
      - name: url
        value: $(params.git-repo)
      - name: revision
        value: $(params.git-commit)
  - name: pipeline-run
    resource:
      apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: sample-spring-boot-$(uid)
      spec:
        pipelineRef:
          name: sample-spring-boot
        resources:
        - name: source-repo
          resourceRef:
            name: source-repo
        params:
        - name: git-branch
          value: $(params.git-branch)
