apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: sample-spring-boot-trigger
spec:
  serviceAccountName: pipeline
  bindings:
   - ref: sample-spring-boot
  template:
   name: sample-spring-boot
